### ISSUE TITLE
How to change dataset from CSI300 to CSI00

### ISSUE THREAD

**Issue by markone1** [Wentao-Xu/HIST#16]
Dear authors, 

I am really interested about your paper, but there are some problems when I tried to make some change to the dataset.

The publiced data file only contains data from CSI300, but now I want to change dataset from CSI300 to CSI100. How can I get data like "csi300_market_value_07to20", "csi300_market_value_07to20", etc.

Thank you for your help

**Comment by LarryLinyz** [comment]
Yes, I have the same question. Appreciate that if the authors can share more infos about this.

**Comment by Wentao-Xu** [comment]
Hi, the CSI 100 is a  subset of CSI 300, it would also use the data file csi300_market_value_07to20.
