### ISSUE TITLE
Accepted for Publication?

### ISSUE THREAD

**Issue by DoThingYo** [Wentao-Xu/HIST#2]
Dear Author,

Interesting work! I wonder if this paper is already accepted by a top conference or not. Could you please reveal some information about the publication? Thanks a lot.

Best regards,
Shaun

**Comment by Wentao-Xu** [comment]
Hi, this paper has not been accepted by a conference or journal, and currently, it is just a pre-print version.

**Comment by DoThingYo** [comment]
> Hi, this paper has not been accepted by a conference or journal, and currently, it is just a pre-print version.

Dear Author,

Thanks so much for your reply. Sincerely wish it's accepted quickly~ Is it convenient to give some hints about which conference you're going to submit? If it's going to appear in a top conference or journal, I might plan to do some follow-up works.

Best regards,
Shaun

**Comment by Wentao-Xu** [comment]
I appreciate your attention to our work. I will let you know as soon as it is accepted by a conference or a journal.

**Comment by DoThingYo** [comment]
Waiting for your good news!
