### ISSUE TITLE
About calculate the cos similarity

### ISSUE THREAD

**Issue by Axl-zhang** [Wentao-Xu/HIST#3]
i_shared_info, hidden in model.py line 116,  are you calculate the same tensor?  it seems hidden is equal to i_shared_info, even if i debug and step in cal_cos_similarity, the two paramters of cal_cos_similarity function is the same

# Hidden Concept Module
        i_shared_info = x_hidden - e_shared_back
        hidden = i_shared_info
        i_stock_to_concept = cal_cos_similarity(i_shared_info, hidden)

**Comment by Wentao-Xu** [comment]
Yes, as you can see in Section 4.3 of our paper, we use stock embedding to initialize the hidden concept embedding.
To better understand the code, I suggest you read our paper first.
