### ISSUE TITLE
What does Precision@N mean?

### ISSUE THREAD

**Issue by BoruiXu** [Wentao-Xu/HIST#7]
Dear author:

Thanks for your work! I read your paper but I have some questions about the evaluation metrics. I am confused about Precision@N. According to Appendix A.2., “The Precision@N is the proportion of top N predictions on each day with the positive label.” I don't understand what that means, maybe sometimes almost all stocks have negative labels, in addition I find the recall metrics are not satisfactory.

Looking forward to your reply!

**Comment by Wentao-Xu** [comment]
Hi, the top N predictions are the N stocks with the largest prediction scores on each day (we sort the stocks on each day according to their prediction scores), and Precision@N is the proportion of top N predictions on each day with the positive label.

**Comment by a919480698** [comment]
Thanks for your reply! 
I understand how to calculate Precision@N, but I am confused about the meaning of it. For example, if I predict that all the scores are positive if the Precision@N is 1?

**Comment by Wentao-Xu** [comment]
Yes, if all the labels of the top N prediction are positive, then the Precision@N is 1. 
In the stock investment, since we do not know the stock future trends, we will invest the top N stocks with the largest prediction scores and hope that those N stocks would gain more positive returns.

**Comment by BoruiXu** [comment]
Thanks a lot!
