### ISSUE TITLE
How to get the stock2concept_matrix?

### ISSUE THREAD

**Issue by polaris-gogh** [Wentao-Xu/HIST#9]
Dear author, can you provide the specific code to get stock2concept_matrix? Thanks.

**Comment by Wentao-Xu** [comment]
Hi, you do not need the code to get stock2concept_matrix. You can directly use the stock2concept_matrix I provided.

**Comment by polaris-gogh** [comment]
> Hi, you do not need the code to get stock2concept_matrix. You can directly use the stock2concept_matrix I provided.

Actually I want to know how to get the stock2concept_matrix when I use different instruments. In my opinion, each column represents a conecpt and made by one-hot encoding. Is it right?

**Comment by Wentao-Xu** [comment]
The code to generate stock2concept_matrix is extremely complicated. So I suggest you not use different instruments and directly use the instruments we provided.

**Comment by polaris-gogh** [comment]
Thank you for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wentao ***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 下午5:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Wentao-Xu/HIST] How to get the stock2concept_matrix? (Issue #9)





 
The code to generate stock2concept_matrix is extremely complicated. So I suggest you not use different instruments and directly use the instruments we provided.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
